# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 705)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setSpacing(9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Setup = QtWidgets.QTabWidget(self.centralwidget)
        self.Setup.setObjectName("Setup")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_11.setMaximumSize(QtCore.QSize(350, 160))
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_19 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_21 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.flightdur = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.flightdur.setFont(font)
        self.flightdur.setAlignment(QtCore.Qt.AlignCenter)
        self.flightdur.setObjectName("flightdur")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.flightdur)
        self.pardeploy = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pardeploy.setFont(font)
        self.pardeploy.setAlignment(QtCore.Qt.AlignCenter)
        self.pardeploy.setObjectName("pardeploy")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pardeploy)
        self.groundhit = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groundhit.setFont(font)
        self.groundhit.setAlignment(QtCore.Qt.AlignCenter)
        self.groundhit.setObjectName("groundhit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.groundhit)
        self.gridLayout_21.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(19999, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.plotlayout = QtWidgets.QGridLayout()
        self.plotlayout.setObjectName("plotlayout")
        self.gridLayout_15.addLayout(self.plotlayout, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 403))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gyrolayout = QtWidgets.QGridLayout()
        self.gyrolayout.setObjectName("gyrolayout")
        self.gridLayout_9.addLayout(self.gyrolayout, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.gridLayout_24.addLayout(self.gridLayout_23, 2, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(-1, 9, 8, 9)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 5, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 1, 8, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 6, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 1, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 8, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 1, 0, 1, 1)
        self.gridLayout_24.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(650, 130))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16666, 160))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sangch = QtWidgets.QCheckBox(self.groupBox_2)
        self.sangch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.sangch.setText("")
        self.sangch.setObjectName("sangch")
        self.gridLayout_3.addWidget(self.sangch, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 1, 1, 1)
        self.sangval = QtWidgets.QLabel(self.groupBox_2)
        self.sangval.setObjectName("sangval")
        self.gridLayout_3.addWidget(self.sangval, 0, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 13, 1, 1)
        self.aangval = QtWidgets.QLabel(self.groupBox_2)
        self.aangval.setObjectName("aangval")
        self.gridLayout_3.addWidget(self.aangval, 0, 8, 1, 1)
        self.t2val = QtWidgets.QLabel(self.groupBox_2)
        self.t2val.setObjectName("t2val")
        self.gridLayout_3.addWidget(self.t2val, 0, 14, 1, 1)
        self.latitudeval = QtWidgets.QLabel(self.groupBox_2)
        self.latitudeval.setObjectName("latitudeval")
        self.gridLayout_3.addWidget(self.latitudeval, 0, 11, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 0, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 10, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.groupBox_2)
        self.label_74.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_74.setText("")
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 0, 3, 1, 1)
        self.aangch = QtWidgets.QCheckBox(self.groupBox_2)
        self.aangch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.aangch.setText("")
        self.aangch.setObjectName("aangch")
        self.gridLayout_3.addWidget(self.aangch, 0, 6, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_76.setText("")
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 0, 9, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.groupBox_2)
        self.label_93.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_93.setText("")
        self.label_93.setObjectName("label_93")
        self.gridLayout_3.addWidget(self.label_93, 0, 12, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 0, 1, 2)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_64 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_8.addWidget(self.label_64, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_8.addWidget(self.label_73, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_8.addWidget(self.label_71, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_68 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_8.addWidget(self.label_68, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_8, 0, 0, 1, 2)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setText("")
        self.label_66.setObjectName("label_66")
        self.gridLayout_12.addWidget(self.label_66, 0, 5, 1, 1)
        self.atopval = QtWidgets.QLabel(self.groupBox_2)
        self.atopval.setObjectName("atopval")
        self.gridLayout_12.addWidget(self.atopval, 0, 8, 1, 1)
        self.longval = QtWidgets.QLabel(self.groupBox_2)
        self.longval.setObjectName("longval")
        self.gridLayout_12.addWidget(self.longval, 0, 11, 1, 1)
        self.t3val = QtWidgets.QLabel(self.groupBox_2)
        self.t3val.setObjectName("t3val")
        self.gridLayout_12.addWidget(self.t3val, 0, 14, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.groupBox_2)
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.gridLayout_12.addWidget(self.label_67, 0, 4, 1, 1)
        self.stopval = QtWidgets.QLabel(self.groupBox_2)
        self.stopval.setObjectName("stopval")
        self.gridLayout_12.addWidget(self.stopval, 0, 2, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.groupBox_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_12.addWidget(self.label_63, 0, 10, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.groupBox_2)
        self.label_75.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.gridLayout_12.addWidget(self.label_75, 0, 3, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.groupBox_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_12.addWidget(self.label_62, 0, 7, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_2)
        self.label_69.setObjectName("label_69")
        self.gridLayout_12.addWidget(self.label_69, 0, 13, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.groupBox_2)
        self.label_80.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_80.setText("")
        self.label_80.setObjectName("label_80")
        self.gridLayout_12.addWidget(self.label_80, 0, 12, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        self.label_77.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_77.setText("")
        self.label_77.setObjectName("label_77")
        self.gridLayout_12.addWidget(self.label_77, 0, 9, 1, 1)
        self.atopch = QtWidgets.QCheckBox(self.groupBox_2)
        self.atopch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.atopch.setText("")
        self.atopch.setObjectName("atopch")
        self.gridLayout_12.addWidget(self.atopch, 0, 6, 1, 1)
        self.stopch = QtWidgets.QCheckBox(self.groupBox_2)
        self.stopch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.stopch.setText("")
        self.stopch.setObjectName("stopch")
        self.gridLayout_12.addWidget(self.stopch, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_12, 5, 0, 1, 2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 0, 7, 1, 1)
        self.shorch = QtWidgets.QCheckBox(self.groupBox_2)
        self.shorch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.shorch.setText("")
        self.shorch.setObjectName("shorch")
        self.gridLayout_5.addWidget(self.shorch, 0, 0, 1, 1)
        self.ahorval = QtWidgets.QLabel(self.groupBox_2)
        self.ahorval.setObjectName("ahorval")
        self.gridLayout_5.addWidget(self.ahorval, 0, 8, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 0, 10, 1, 1)
        self.phorval = QtWidgets.QLabel(self.groupBox_2)
        self.phorval.setObjectName("phorval")
        self.gridLayout_5.addWidget(self.phorval, 0, 11, 1, 1)
        self.orolval = QtWidgets.QLabel(self.groupBox_2)
        self.orolval.setObjectName("orolval")
        self.gridLayout_5.addWidget(self.orolval, 0, 5, 1, 1)
        self.t1val = QtWidgets.QLabel(self.groupBox_2)
        self.t1val.setObjectName("t1val")
        self.gridLayout_5.addWidget(self.t1val, 0, 14, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_5.addWidget(self.label_38, 0, 13, 1, 1)
        self.shorval = QtWidgets.QLabel(self.groupBox_2)
        self.shorval.setObjectName("shorval")
        self.gridLayout_5.addWidget(self.shorval, 0, 2, 1, 1)
        self.orolch = QtWidgets.QCheckBox(self.groupBox_2)
        self.orolch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.orolch.setText("")
        self.orolch.setObjectName("orolch")
        self.gridLayout_5.addWidget(self.orolch, 0, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 4, 1, 1)
        self.ahorch = QtWidgets.QCheckBox(self.groupBox_2)
        self.ahorch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.ahorch.setText("")
        self.ahorch.setObjectName("ahorch")
        self.gridLayout_5.addWidget(self.ahorch, 0, 6, 1, 1)
        self.phorch = QtWidgets.QCheckBox(self.groupBox_2)
        self.phorch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.phorch.setText("")
        self.phorch.setObjectName("phorch")
        self.gridLayout_5.addWidget(self.phorch, 0, 9, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.groupBox_2)
        self.label_92.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_92.setText("")
        self.label_92.setObjectName("label_92")
        self.gridLayout_5.addWidget(self.label_92, 0, 12, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 0, 1, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.sabsch = QtWidgets.QCheckBox(self.groupBox_2)
        self.sabsch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.sabsch.setText("")
        self.sabsch.setObjectName("sabsch")
        self.gridLayout_7.addWidget(self.sabsch, 0, 0, 1, 1)
        self.opitch = QtWidgets.QCheckBox(self.groupBox_2)
        self.opitch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.opitch.setText("")
        self.opitch.setObjectName("opitch")
        self.gridLayout_7.addWidget(self.opitch, 0, 3, 1, 1)
        self.comsval = QtWidgets.QLabel(self.groupBox_2)
        self.comsval.setObjectName("comsval")
        self.gridLayout_7.addWidget(self.comsval, 0, 14, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBox_2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 0, 10, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 0, 4, 1, 1)
        self.sabsval = QtWidgets.QLabel(self.groupBox_2)
        self.sabsval.setObjectName("sabsval")
        self.gridLayout_7.addWidget(self.sabsval, 0, 2, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBox_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 0, 7, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 0, 13, 1, 1)
        self.aabsval = QtWidgets.QLabel(self.groupBox_2)
        self.aabsval.setObjectName("aabsval")
        self.gridLayout_7.addWidget(self.aabsval, 0, 8, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_7.addWidget(self.label_54, 0, 1, 1, 1)
        self.pabsval = QtWidgets.QLabel(self.groupBox_2)
        self.pabsval.setObjectName("pabsval")
        self.gridLayout_7.addWidget(self.pabsval, 0, 11, 1, 1)
        self.opitval = QtWidgets.QLabel(self.groupBox_2)
        self.opitval.setObjectName("opitval")
        self.gridLayout_7.addWidget(self.opitval, 0, 5, 1, 1)
        self.aabsch = QtWidgets.QCheckBox(self.groupBox_2)
        self.aabsch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.aabsch.setText("")
        self.aabsch.setObjectName("aabsch")
        self.gridLayout_7.addWidget(self.aabsch, 0, 6, 1, 1)
        self.pabsch = QtWidgets.QCheckBox(self.groupBox_2)
        self.pabsch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.pabsch.setText("")
        self.pabsch.setObjectName("pabsch")
        self.gridLayout_7.addWidget(self.pabsch, 0, 9, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.groupBox_2)
        self.label_79.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_79.setText("")
        self.label_79.setObjectName("label_79")
        self.gridLayout_7.addWidget(self.label_79, 0, 12, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 1, 0, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.oyawch = QtWidgets.QCheckBox(self.groupBox_2)
        self.oyawch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.oyawch.setText("")
        self.oyawch.setObjectName("oyawch")
        self.gridLayout_6.addWidget(self.oyawch, 0, 3, 1, 1)
        self.sverch = QtWidgets.QCheckBox(self.groupBox_2)
        self.sverch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.sverch.setText("")
        self.sverch.setObjectName("sverch")
        self.gridLayout_6.addWidget(self.sverch, 0, 0, 1, 1)
        self.sverval = QtWidgets.QLabel(self.groupBox_2)
        self.sverval.setObjectName("sverval")
        self.gridLayout_6.addWidget(self.sverval, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 0, 7, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 0, 13, 1, 1)
        self.averval = QtWidgets.QLabel(self.groupBox_2)
        self.averval.setObjectName("averval")
        self.gridLayout_6.addWidget(self.averval, 0, 8, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBox_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 0, 10, 1, 1)
        self.parachuteval = QtWidgets.QLabel(self.groupBox_2)
        self.parachuteval.setObjectName("parachuteval")
        self.gridLayout_6.addWidget(self.parachuteval, 0, 14, 1, 1)
        self.paltval = QtWidgets.QLabel(self.groupBox_2)
        self.paltval.setObjectName("paltval")
        self.gridLayout_6.addWidget(self.paltval, 0, 11, 1, 1)
        self.oyawval = QtWidgets.QLabel(self.groupBox_2)
        self.oyawval.setObjectName("oyawval")
        self.gridLayout_6.addWidget(self.oyawval, 0, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 0, 4, 1, 1)
        self.averch = QtWidgets.QCheckBox(self.groupBox_2)
        self.averch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.averch.setText("")
        self.averch.setObjectName("averch")
        self.gridLayout_6.addWidget(self.averch, 0, 6, 1, 1)
        self.paltch = QtWidgets.QCheckBox(self.groupBox_2)
        self.paltch.setMaximumSize(QtCore.QSize(13, 16777215))
        self.paltch.setText("")
        self.paltch.setObjectName("paltch")
        self.gridLayout_6.addWidget(self.paltch, 0, 9, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.groupBox_2)
        self.label_78.setMaximumSize(QtCore.QSize(13, 16777215))
        self.label_78.setText("")
        self.label_78.setObjectName("label_78")
        self.gridLayout_6.addWidget(self.label_78, 0, 12, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 2, 0, 1, 2)
        self.gridLayout_24.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.Setup.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setMinimumSize(QtCore.QSize(575, 0))
        self.groupBox_8.setMaximumSize(QtCore.QSize(575, 60))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_45 = QtWidgets.QLabel(self.groupBox_8)
        self.label_45.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_45.setObjectName("label_45")
        self.gridLayout_14.addWidget(self.label_45, 0, 0, 1, 1)
        self.yaxisname = QtWidgets.QComboBox(self.groupBox_8)
        self.yaxisname.setMinimumSize(QtCore.QSize(120, 0))
        self.yaxisname.setMaximumSize(QtCore.QSize(120, 16777215))
        self.yaxisname.setObjectName("yaxisname")
        self.gridLayout_14.addWidget(self.yaxisname, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_8)
        self.label_35.setMaximumSize(QtCore.QSize(14, 16777215))
        self.label_35.setObjectName("label_35")
        self.gridLayout_14.addWidget(self.label_35, 0, 4, 1, 1)
        self.plotname = QtWidgets.QLineEdit(self.groupBox_8)
        self.plotname.setMinimumSize(QtCore.QSize(100, 0))
        self.plotname.setMaximumSize(QtCore.QSize(100, 16777215))
        self.plotname.setObjectName("plotname")
        self.gridLayout_14.addWidget(self.plotname, 0, 1, 1, 1)
        self.xaxisname = QtWidgets.QComboBox(self.groupBox_8)
        self.xaxisname.setMinimumSize(QtCore.QSize(120, 0))
        self.xaxisname.setMaximumSize(QtCore.QSize(120, 16777215))
        self.xaxisname.setObjectName("xaxisname")
        self.gridLayout_14.addWidget(self.xaxisname, 0, 3, 1, 1)
        self.baddplot = QtWidgets.QPushButton(self.groupBox_8)
        self.baddplot.setMinimumSize(QtCore.QSize(60, 0))
        self.baddplot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.baddplot.setObjectName("baddplot")
        self.gridLayout_14.addWidget(self.baddplot, 0, 6, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_9.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.listdelplot = QtWidgets.QComboBox(self.groupBox_9)
        self.listdelplot.setMinimumSize(QtCore.QSize(120, 0))
        self.listdelplot.setMaximumSize(QtCore.QSize(120, 16777215))
        self.listdelplot.setObjectName("listdelplot")
        self.gridLayout_17.addWidget(self.listdelplot, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBox_9)
        self.label_52.setMinimumSize(QtCore.QSize(30, 0))
        self.label_52.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_52.setObjectName("label_52")
        self.gridLayout_17.addWidget(self.label_52, 0, 0, 1, 1)
        self.bdelplot = QtWidgets.QPushButton(self.groupBox_9)
        self.bdelplot.setMinimumSize(QtCore.QSize(60, 0))
        self.bdelplot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bdelplot.setObjectName("bdelplot")
        self.gridLayout_17.addWidget(self.bdelplot, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_9, 0, 1, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox_12.setMaximumSize(QtCore.QSize(175, 16777215))
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.bopenlog = QtWidgets.QPushButton(self.groupBox_12)
        self.bopenlog.setObjectName("bopenlog")
        self.gridLayout_10.addWidget(self.bopenlog, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_12, 0, 2, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.flightanlayout = QtWidgets.QGridLayout()
        self.flightanlayout.setObjectName("flightanlayout")
        self.gridLayout_16.addLayout(self.flightanlayout, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_5, 1, 0, 1, 4)
        self.Setup.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.consolewin = QtWidgets.QTextEdit(self.tab_4)
        self.consolewin.setObjectName("consolewin")
        self.gridLayout_13.addWidget(self.consolewin, 0, 0, 1, 1)
        self.Setup.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(9, 9, 205, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox_7)
        self.label_70.setObjectName("label_70")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_70)
        self.receivername = QtWidgets.QLineEdit(self.groupBox_7)
        self.receivername.setObjectName("receivername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.receivername)
        self.label_72 = QtWidgets.QLabel(self.groupBox_7)
        self.label_72.setObjectName("label_72")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_72)
        self.receiverbaudrate = QtWidgets.QLineEdit(self.groupBox_7)
        self.receiverbaudrate.setObjectName("receiverbaudrate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.receiverbaudrate)
        self.gridLayout_18.addLayout(self.formLayout, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 100, 205, 317))
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_55 = QtWidgets.QLabel(self.groupBox_10)
        self.label_55.setObjectName("label_55")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.label_81 = QtWidgets.QLabel(self.groupBox_10)
        self.label_81.setObjectName("label_81")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_81)
        self.label_82 = QtWidgets.QLabel(self.groupBox_10)
        self.label_82.setObjectName("label_82")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_82)
        self.label_83 = QtWidgets.QLabel(self.groupBox_10)
        self.label_83.setObjectName("label_83")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_83)
        self.label_84 = QtWidgets.QLabel(self.groupBox_10)
        self.label_84.setObjectName("label_84")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.label_85 = QtWidgets.QLabel(self.groupBox_10)
        self.label_85.setObjectName("label_85")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.label_86 = QtWidgets.QLabel(self.groupBox_10)
        self.label_86.setObjectName("label_86")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_86)
        self.label_87 = QtWidgets.QLabel(self.groupBox_10)
        self.label_87.setObjectName("label_87")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_87)
        self.label_88 = QtWidgets.QLabel(self.groupBox_10)
        self.label_88.setObjectName("label_88")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_88)
        self.label_89 = QtWidgets.QLabel(self.groupBox_10)
        self.label_89.setObjectName("label_89")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_89)
        self.label_90 = QtWidgets.QLabel(self.groupBox_10)
        self.label_90.setObjectName("label_90")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_90)
        self.label_91 = QtWidgets.QLabel(self.groupBox_10)
        self.label_91.setObjectName("label_91")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_91)
        self.data1 = QtWidgets.QComboBox(self.groupBox_10)
        self.data1.setObjectName("data1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.data1)
        self.data2 = QtWidgets.QComboBox(self.groupBox_10)
        self.data2.setObjectName("data2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.data2)
        self.data3 = QtWidgets.QComboBox(self.groupBox_10)
        self.data3.setObjectName("data3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.data3)
        self.data4 = QtWidgets.QComboBox(self.groupBox_10)
        self.data4.setObjectName("data4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.data4)
        self.data5 = QtWidgets.QComboBox(self.groupBox_10)
        self.data5.setObjectName("data5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.data5)
        self.data6 = QtWidgets.QComboBox(self.groupBox_10)
        self.data6.setObjectName("data6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.data6)
        self.data7 = QtWidgets.QComboBox(self.groupBox_10)
        self.data7.setObjectName("data7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.data7)
        self.data8 = QtWidgets.QComboBox(self.groupBox_10)
        self.data8.setObjectName("data8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.data8)
        self.data9 = QtWidgets.QComboBox(self.groupBox_10)
        self.data9.setObjectName("data9")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.data9)
        self.data10 = QtWidgets.QComboBox(self.groupBox_10)
        self.data10.setObjectName("data10")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.data10)
        self.data11 = QtWidgets.QComboBox(self.groupBox_10)
        self.data11.setObjectName("data11")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.data11)
        self.data12 = QtWidgets.QComboBox(self.groupBox_10)
        self.data12.setObjectName("data12")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.data12)
        self.gridLayout_19.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 430, 206, 77))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_94 = QtWidgets.QLabel(self.groupBox_6)
        self.label_94.setObjectName("label_94")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_94)
        self.rocketmodel = QtWidgets.QComboBox(self.groupBox_6)
        self.rocketmodel.setObjectName("rocketmodel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rocketmodel)
        self.label_95 = QtWidgets.QLabel(self.groupBox_6)
        self.label_95.setObjectName("label_95")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_95)
        self.rockettexture = QtWidgets.QComboBox(self.groupBox_6)
        self.rockettexture.setObjectName("rockettexture")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rockettexture)
        self.gridLayout_20.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.Setup.addTab(self.tab_3, "")
        self.gridLayout_4.addWidget(self.Setup, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")

        self.retranslateUi(MainWindow)
        self.Setup.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Apex Flight Monitor"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Mission Status"))
        self.label_17.setText(_translate("MainWindow", "Flight duration"))
        self.label_19.setText(_translate("MainWindow", "Parachute deploy"))
        self.label_21.setText(_translate("MainWindow", "Ground hit"))
        self.flightdur.setText(_translate("MainWindow", "N/A"))
        self.pardeploy.setText(_translate("MainWindow", "N/A"))
        self.groundhit.setText(_translate("MainWindow", "N/A"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Plot"))
        self.groupBox_4.setTitle(_translate("MainWindow", "3D View"))
        self.groupBox.setTitle(_translate("MainWindow", "Stages"))
        self.label_6.setText(_translate("MainWindow", "N/A"))
        self.label_4.setText(_translate("MainWindow", "Apogee"))
        self.label_8.setText(_translate("MainWindow", "N/A"))
        self.label.setText(_translate("MainWindow", "Ignition"))
        self.label_11.setText(_translate("MainWindow", "Parachute descent"))
        self.label_3.setText(_translate("MainWindow", "Free Ascension"))
        self.label_5.setText(_translate("MainWindow", "N/A"))
        self.label_13.setText(_translate("MainWindow", "N/A"))
        self.label_26.setText(_translate("MainWindow", "N/A"))
        self.label_24.setText(_translate("MainWindow", "N/A"))
        self.label_9.setText(_translate("MainWindow", "Free descent"))
        self.label_7.setText(_translate("MainWindow", "N/A"))
        self.label_25.setText(_translate("MainWindow", "N/A"))
        self.label_10.setText(_translate("MainWindow", "Parachute deployment"))
        self.label_2.setText(_translate("MainWindow", "Thrusted ascension"))
        self.label_12.setText(_translate("MainWindow", "Ground"))
        self.label_37.setText(_translate("MainWindow", "Preflight check"))
        self.label_39.setText(_translate("MainWindow", "Not ready"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Flight data"))
        self.label_14.setText(_translate("MainWindow", "Angular"))
        self.sangval.setText(_translate("MainWindow", "N/A"))
        self.label_16.setText(_translate("MainWindow", "Angular"))
        self.label_20.setText(_translate("MainWindow", "T1"))
        self.aangval.setText(_translate("MainWindow", "N/A"))
        self.t2val.setText(_translate("MainWindow", "N/A"))
        self.latitudeval.setText(_translate("MainWindow", "N/A"))
        self.label_18.setText(_translate("MainWindow", "Latitude"))
        self.label_64.setText(_translate("MainWindow", "Speed"))
        self.label_73.setText(_translate("MainWindow", "Health"))
        self.label_71.setText(_translate("MainWindow", "Position"))
        self.label_68.setText(_translate("MainWindow", "Acceleration"))
        self.label_22.setText(_translate("MainWindow", "Orientation"))
        self.atopval.setText(_translate("MainWindow", "N/A"))
        self.longval.setText(_translate("MainWindow", "N/A"))
        self.t3val.setText(_translate("MainWindow", "N/A"))
        self.stopval.setText(_translate("MainWindow", "N/A"))
        self.label_63.setText(_translate("MainWindow", "Longitude"))
        self.label_42.setText(_translate("MainWindow", "Top"))
        self.label_62.setText(_translate("MainWindow", "Top"))
        self.label_69.setText(_translate("MainWindow", "T2"))
        self.label_36.setText(_translate("MainWindow", "Horizontal"))
        self.ahorval.setText(_translate("MainWindow", "N/A"))
        self.label_34.setText(_translate("MainWindow", "Horizontal"))
        self.label_40.setText(_translate("MainWindow", "Horizontal"))
        self.phorval.setText(_translate("MainWindow", "N/A"))
        self.orolval.setText(_translate("MainWindow", "N/A"))
        self.t1val.setText(_translate("MainWindow", "Offline"))
        self.label_38.setText(_translate("MainWindow", "GPS"))
        self.shorval.setText(_translate("MainWindow", "N/A"))
        self.label_30.setText(_translate("MainWindow", "Roll"))
        self.comsval.setText(_translate("MainWindow", "Offline"))
        self.label_60.setText(_translate("MainWindow", "Abs. Dist."))
        self.label_23.setText(_translate("MainWindow", "Pitch"))
        self.sabsval.setText(_translate("MainWindow", "N/A"))
        self.label_56.setText(_translate("MainWindow", "Abs."))
        self.label_58.setText(_translate("MainWindow", "Coms"))
        self.aabsval.setText(_translate("MainWindow", "N/A"))
        self.label_54.setText(_translate("MainWindow", "Abs."))
        self.pabsval.setText(_translate("MainWindow", "N/A"))
        self.opitval.setText(_translate("MainWindow", "N/A"))
        self.sverval.setText(_translate("MainWindow", "N/A"))
        self.label_44.setText(_translate("MainWindow", "Vertical"))
        self.label_46.setText(_translate("MainWindow", "Vertical"))
        self.label_48.setText(_translate("MainWindow", "Parachute"))
        self.averval.setText(_translate("MainWindow", "N/A"))
        self.label_50.setText(_translate("MainWindow", "Altitude"))
        self.parachuteval.setText(_translate("MainWindow", "Online"))
        self.paltval.setText(_translate("MainWindow", "N/A"))
        self.oyawval.setText(_translate("MainWindow", "N/A"))
        self.label_28.setText(_translate("MainWindow", "Yaw"))
        self.Setup.setTabText(self.Setup.indexOf(self.tab), _translate("MainWindow", "Flight Summary"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Add plot"))
        self.label_45.setText(_translate("MainWindow", "Name"))
        self.label_15.setText(_translate("MainWindow", "X"))
        self.label_35.setText(_translate("MainWindow", "Y"))
        self.baddplot.setText(_translate("MainWindow", "Add"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Remove plot"))
        self.label_52.setText(_translate("MainWindow", "Name"))
        self.bdelplot.setText(_translate("MainWindow", "Remove"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Open flight log"))
        self.bopenlog.setText(_translate("MainWindow", "Select file"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Plots"))
        self.Setup.setTabText(self.Setup.indexOf(self.tab_2), _translate("MainWindow", "Flight Analysis"))
        self.Setup.setTabText(self.Setup.indexOf(self.tab_4), _translate("MainWindow", "Console"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Receiver"))
        self.label_70.setText(_translate("MainWindow", "Name"))
        self.label_72.setText(_translate("MainWindow", "Baudrate"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Data sequence"))
        self.label_55.setText(_translate("MainWindow", "1"))
        self.label_81.setText(_translate("MainWindow", "2"))
        self.label_82.setText(_translate("MainWindow", "3"))
        self.label_83.setText(_translate("MainWindow", "4"))
        self.label_84.setText(_translate("MainWindow", "5"))
        self.label_85.setText(_translate("MainWindow", "6"))
        self.label_86.setText(_translate("MainWindow", "7"))
        self.label_87.setText(_translate("MainWindow", "8"))
        self.label_88.setText(_translate("MainWindow", "9"))
        self.label_89.setText(_translate("MainWindow", "10"))
        self.label_90.setText(_translate("MainWindow", "11"))
        self.label_91.setText(_translate("MainWindow", "12"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Rocket model"))
        self.label_94.setText(_translate("MainWindow", "Model"))
        self.label_95.setText(_translate("MainWindow", "Texture"))
        self.Setup.setTabText(self.Setup.indexOf(self.tab_3), _translate("MainWindow", "Setup"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))


